# Generated by Django 4.2.19 on 2025-03-10 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                ("firstname", models.CharField(db_column="FirstName", max_length=225)),
                ("lastname", models.CharField(db_column="LastName", max_length=225)),
                (
                    "username",
                    models.CharField(
                        db_column="UserName",
                        max_length=225,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("password", models.CharField(db_column="Password", max_length=255)),
                ("role", models.CharField(db_column="Role", max_length=18)),
                ("is_active", models.IntegerField()),
                ("is_staff", models.IntegerField()),
                ("is_superuser", models.IntegerField()),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "db_table": "users",
            },
        ),
    ]
